### ISSUE TITLE
Dot

### ISSUE THREAD

**Issue by KronicDeth** [KronicDeth/intellij-elixir#30]
Handle [`dot`](https://github.com/elixir-lang/elixir/blob/de39bbaca277002797e52ffbde617ace06233a2b/lib/elixir/src/elixir_tokenizer.erl#L434-L436), which needs the rest to be [operators](https://github.com/elixir-lang/elixir/blob/de39bbaca277002797e52ffbde617ace06233a2b/lib/elixir/src/elixir_tokenizer.erl#L561-L578) (so complete #29 first), [`(`](https://github.com/elixir-lang/elixir/blob/de39bbaca277002797e52ffbde617ace06233a2b/lib/elixir/src/elixir_tokenizer.erl#L580-L582) for anonymous function calls and [interpolated function names](https://github.com/elixir-lang/elixir/blob/de39bbaca277002797e52ffbde617ace06233a2b/lib/elixir/src/elixir_tokenizer.erl#L584-L596).  (For example, `Keyword."get"([a: 1], :a)` is valid and the same as `Keyword.get([a: 1], :a)`, so you can use a string or char list the after dot the same way you pass Symbols to `send` in Ruby.)  Finally, there is normal `.` call syntax.  All these forms need to accept multiple newlines and whitespace on either side of the `.`.

# Right Operand
- [x] [`.<three-token-operator>`](https://github.com/elixir-lang/elixir/blob/de39bbaca277002797e52ffbde617ace06233a2b/lib/elixir/src/elixir_tokenizer.erl#L561-L565) (#114)
- [x] [`.<two-token-operator>`](https://github.com/elixir-lang/elixir/blob/de39bbaca277002797e52ffbde617ace06233a2b/lib/elixir/src/elixir_tokenizer.erl#L567-L572) (#114)
- [x] [`.<one-token-operator>`](https://github.com/elixir-lang/elixir/blob/de39bbaca277002797e52ffbde617ace06233a2b/lib/elixir/src/elixir_tokenizer.erl#L574-L578) (#114)
- [x] [`.(`](https://github.com/elixir-lang/elixir/blob/de39bbaca277002797e52ffbde617ace06233a2b/lib/elixir/src/elixir_tokenizer.erl#L580-L582)
  - [x] [`parens_call`](https://github.com/elixir-lang/elixir/blob/39b6789a8625071e149f0a7347ca7a2111f7c8f2/lib/elixir/src/elixir_parser.yrl#L430)
    - ~~[ ] [`block_expr`](https://github.com/elixir-lang/elixir/blob/39b6789a8625071e149f0a7347ca7a2111f7c8f2/lib/elixir/src/elixir_parser.yrl#L150-L151)~~
      - ~~[ ] [`unmatched_expr`](https://github.com/elixir-lang/elixir/blob/39b6789a8625071e149f0a7347ca7a2111f7c8f2/lib/elixir/src/elixir_parser.yrl#L148)~~ (*Moved to #116*)
        - ~~[ ] [`expr`](https://github.com/elixir-lang/elixir/blob/39b6789a8625071e149f0a7347ca7a2111f7c8f2/lib/elixir/src/elixir_parser.yrl#L91)~~
    - ~~[ ] [`max_expr`](https://github.com/elixir-lang/elixir/blob/39b6789a8625071e149f0a7347ca7a2111f7c8f2/lib/elixir/src/elixir_parser.yrl#L254-L255)~~ (*Can't be in max_expr because use of matchedExpression requires it extending matchedExpression and being a direct child of matchedExpression*
      - ~~[ ] [`access_expr`](https://github.com/elixir-lang/elixir/blob/39b6789a8625071e149f0a7347ca7a2111f7c8f2/lib/elixir/src/elixir_parser.yrl#L248)~~
  - [x] [`call_args_parens`](https://github.com/elixir-lang/elixir/blob/39b6789a8625071e149f0a7347ca7a2111f7c8f2/lib/elixir/src/elixir_parser.yrl#L484-L488)
    - [x] [`kw`](https://github.com/elixir-lang/elixir/blob/39b6789a8625071e149f0a7347ca7a2111f7c8f2/lib/elixir/src/elixir_parser.yrl#L502-L503)
    - [x] [`call_args_parens_base`](https://github.com/elixir-lang/elixir/blob/39b6789a8625071e149f0a7347ca7a2111f7c8f2/lib/elixir/src/elixir_parser.yrl#L481-L482)
      - [x] [`call_args_parens_expr`](https://github.com/elixir-lang/elixir/blob/39b6789a8625071e149f0a7347ca7a2111f7c8f2/lib/elixir/src/elixir_parser.yrl#L477-L479)
- [x] [`.<string>`](https://github.com/elixir-lang/elixir/blob/de39bbaca277002797e52ffbde617ace06233a2b/lib/elixir/src/elixir_tokenizer.erl#L584-L596) (Already complete in #105)
- [x] [`.<char-list>`](https://github.com/elixir-lang/elixir/blob/de39bbaca277002797e52ffbde617ace06233a2b/lib/elixir/src/elixir_tokenizer.erl#L584-L596) (Already completed in #105)

# Call Identifier
- ~~[ ] [`bracket_identifier`](https://github.com/elixir-lang/elixir/blob/de39bbaca277002797e52ffbde617ace06233a2b/lib/elixir/src/elixir_tokenizer.erl#L847)~~
  -  ~~[ ] [`dot_bracket_identifier`](https://github.com/elixir-lang/elixir/blob/de39bbaca277002797e52ffbde617ace06233a2b/lib/elixir/src/elixir_parser.yrl#L396-L397)~~
    - ~~[ ] [`bracket_arg`](https://github.com/elixir-lang/elixir/blob/de39bbaca277002797e52ffbde617ace06233a2b/lib/elixir/src/elixir_parser.yrl#L233-L235)~~
    - ~~[ ] [`bracket_expr`](https://github.com/elixir-lang/elixir/blob/de39bbaca277002797e52ffbde617ace06233a2b/lib/elixir/src/elixir_parser.yrl#L237)~~ (*Moved to #117*)
      - ~~[ ] Add to [`access_expr`](https://github.com/elixir-lang/elixir/blob/de39bbaca277002797e52ffbde617ace06233a2b/lib/elixir/src/elixir_parser.yrl#L201)~~
    - ~~[ ] [`bracket_at_expr`](https://github.com/elixir-lang/elixir/blob/de39bbaca277002797e52ffbde617ace06233a2b/lib/elixir/src/elixir_parser.yrl#L240-L241)~~ (*Moved to #117*)
      - ~~[ ] Add to [`access_expr`](https://github.com/elixir-lang/elixir/blob/de39bbaca277002797e52ffbde617ace06233a2b/lib/elixir/src/elixir_parser.yrl#L200)~~
- ~~[ ] [`paren_identifier`](https://github.com/elixir-lang/elixir/blob/de39bbaca277002797e52ffbde617ace06233a2b/lib/elixir/src/elixir_tokenizer.erl#L846)~~ (*Moved to #115*)
  - ~~[ ] [`dot_paren_identifier`](https://github.com/elixir-lang/elixir/blob/de39bbaca277002797e52ffbde617ace06233a2b/lib/elixir/src/elixir_parser.yrl#L399-L400)~~
    - ~~[ ] [`parens_call`](https://github.com/elixir-lang/elixir/blob/de39bbaca277002797e52ffbde617ace06233a2b/lib/elixir/src/elixir_parser.yrl#L402)~~
