### ISSUE TITLE
Max Expression

### ISSUE THREAD

**Issue by KronicDeth** [KronicDeth/intellij-elixir#71]
[`max_expression`](https://github.com/elixir-lang/elixir/blob/de39bbaca277002797e52ffbde617ace06233a2b/lib/elixir/src/elixir_parser.yrl#L226-L231) is [used in `access_expr`](https://github.com/elixir-lang/elixir/blob/de39bbaca277002797e52ffbde617ace06233a2b/lib/elixir/src/elixir_parser.yrl#L223) and [used in `map_expr`](https://github.com/elixir-lang/elixir/blob/de39bbaca277002797e52ffbde617ace06233a2b/lib/elixir/src/elixir_parser.yrl#L498).

# Prereqs
- [x] #50
- [x] #58
- [ ] #68

# Features

## [`access_expr`](https://github.com/elixir-lang/elixir/blob/de39bbaca277002797e52ffbde617ace06233a2b/lib/elixir/src/elixir_parser.yrl#L200-L223) direct-dependencies
- [x] Add `max_expr` to `access_expr`

## [`max_expr`](https://github.com/elixir-lang/elixir/blob/de39bbaca277002797e52ffbde617ace06233a2b/lib/elixir/src/elixir_parser.yrl#L226-L231) direct-dependencies
- [x] [`parens_call`](https://github.com/elixir-lang/elixir/blob/de39bbaca277002797e52ffbde617ace06233a2b/lib/elixir/src/elixir_parser.yrl#L229-L230)
- [x] [`call_args_parens`](https://github.com/elixir-lang/elixir/blob/de39bbaca277002797e52ffbde617ace06233a2b/lib/elixir/src/elixir_parser.yrl#L229-L230)
- [x] [`dot_alias`](https://github.com/elixir-lang/elixir/blob/de39bbaca277002797e52ffbde617ace06233a2b/lib/elixir/src/elixir_parser.yrl#L231)

## [`parens_call`](https://github.com/elixir-lang/elixir/blob/de39bbaca277002797e52ffbde617ace06233a2b/lib/elixir/src/elixir_parser.yrl#L402-L403) direct-dependencies
- [x] [`dot_paren_identifier`](https://github.com/elixir-lang/elixir/blob/de39bbaca277002797e52ffbde617ace06233a2b/lib/elixir/src/elixir_parser.yrl#L402)
- [x] [`dot_call_op`](https://github.com/elixir-lang/elixir/blob/de39bbaca277002797e52ffbde617ace06233a2b/lib/elixir/src/elixir_parser.yrl#L403)

## [`dot_paren_identifer`](https://github.com/elixir-lang/elixir/blob/de39bbaca277002797e52ffbde617ace06233a2b/lib/elixir/src/elixir_parser.yrl#L399-L400) direct dependencies
- [x] [`paren_identifier`](https://github.com/elixir-lang/elixir/blob/de39bbaca277002797e52ffbde617ace06233a2b/lib/elixir/src/elixir_parser.yrl#L399-L400)

## [`dot_call_op`](https://github.com/elixir-lang/elixir/blob/de39bbaca277002797e52ffbde617ace06233a2b/lib/elixir/src/elixir_tokenizer.erl#L582)
- [x] Lex `{DOT_OPERATOR} / {OPENING_PARENTHESES}` as `DOT_CALL_OPERATOR`.

## [`call_args_parens`](https://github.com/elixir-lang/elixir/blob/de39bbaca277002797e52ffbde617ace06233a2b/lib/elixir/src/elixir_parser.yrl#L451-L455)
- [x] Use `emptyParentheses`
- [x] Use `noParenthesesExpression` from #58.
- [x] Use `keywords` from #68
- [x] [`call_args_parens_base`](https://github.com/elixir-lang/elixir/blob/de39bbaca277002797e52ffbde617ace06233a2b/lib/elixir/src/elixir_parser.yrl#L454-L455)

## [`call_args_parens_base`](https://github.com/elixir-lang/elixir/blob/de39bbaca277002797e52ffbde617ace06233a2b/lib/elixir/src/elixir_parser.yrl#L448-L449)
- [x] Use `containerExpression` from #68

**Comment by KronicDeth** [comment]
Resolved by #128
